### ISSUE TITLE
Could not resolve to City.

### ISSUE THREAD

**Issue by RobertoSnap** [BROKLab/brreg-forvalt#41]
Fra Sverre:
<img width="717" alt="CleanShot 2021-11-12 at 13 07 05@2x" src="https://user-images.githubusercontent.com/4772930/141464630-6cfe277e-f7f7-4375-9191-d7eba6f3a82e.png">

Kommer ikke videre i testing. Har prøvd å opprette aksjeeierbok på flere andre selskap og lagt inn andre postnummer f eks 7066, 8909 men får opp samme feilmelding.

- [ ] Opprett samme aksjeierbok med samme postnummer på askjonører
- [ ] Se på loggene i Helpers.
- [ ] Test evt. lokalt i Helpers om library vi bruker for å resolve postnummer ikke har disse.

**Comment by aridder** [comment]
Solved in https://github.com/BROKLab/forvalt/pull/42
